//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cart()
        {
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
        }
    
        public int Id { get; set; }
        public string UserId { get; set; }
        public int ProductId { get; set; }
        public Nullable<bool> Facturado { get; set; }
        public Nullable<System.DateTime> ShopDate { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public string PaymentForm { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public int Cant { get; set; }
        public string TotalPrice { get; set; }
        public string Color { get; set; }
        public string Size { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
    }
}
