//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentPayclub
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string AuthNumber { get; set; }
        public string CreditType { get; set; }
        public string CantMonth { get; set; }
        public string CardType { get; set; }
        public string Subtotal { get; set; }
        public string Iva { get; set; }
        public string Ice { get; set; }
        public string Interes { get; set; }
        public string Total { get; set; }
        public string TransactionId { get; set; }
        public string InvocationType { get; set; }
        public string UserId { get; set; }
        public string Ref1 { get; set; }
        public string Ref2 { get; set; }
        public string Ref3 { get; set; }
        public string Ref4 { get; set; }
        public string Ref5 { get; set; }
    }
}
