//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsDetail
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public string Mark { get; set; }
        public string Details { get; set; }
        public string Specifications { get; set; }
        public string Benefits { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
