//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderConfiguration
    {
        public int Id { get; set; }
        public int ProviderId { get; set; }
        public string PrimaryColor { get; set; }
        public string SecundaryColor { get; set; }
        public string MenuLetersColor { get; set; }
    
        public virtual Provider Provider { get; set; }
    }
}
