//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        public int Id { get; set; }
        public Nullable<int> CartId { get; set; }
        public string PurchaseCode { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public bool IsClosed { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual User User { get; set; }
    }
}
