//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tramaco
    {
        public int Id { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Route { get; set; }
        public string DocumentCosto { get; set; }
        public string FreightCost { get; set; }
        public string DeliveryTime { get; set; }
        public Nullable<bool> Coverage { get; set; }
        public Nullable<bool> HasAgency { get; set; }
        public string ExtraKgCost { get; set; }
    }
}
